name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: 'Documentation'
    label: 'documentation'

  - title: 'Dependencies'
    collapse-after: 5
    labels:
      - 'dependencies'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs\/.+/'
    title:
      - '/doc/i'

  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'

  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/feat/i'

template: |
  ## What’s Changed

  $CHANGES